### ISSUE TITLE
Mismatching version information

### ISSUE THREAD

**Issue by krt16s** [chschtsch/milon-android#1]
You tagged `v0.0.1' but your build.gradle is stating this is

````
versionCode 1
versionName "1.0"
````

If you are unfamiliar with version and versioncodes, please read https://developer.android.com/studio/publish/versioning.html. In short: versionname is a string for the user, versioncode is an integer that should be bumped with every release. Android itself uses it to decided if an apk file is an update or not.

**Comment by chschtsch** [comment]
Whoopsy, thanks for pointing that out!
